#! /bin/sh

autorandr --change

sxhkd &

#bspc monitor -g 1920x1200+0+0

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

# autostart applications
nitrogen --restore &
#/$HOME/.config/autorandr/postswitch &
nm-applet &
xfce4-power-manager &
xfce4-clipman &
ff-theme-util &
fix_xcursor &
blueman-applet &
#Exec=env GTK_THEME=Arc:dark volumeicon &
compton --config ~/.config/compton.conf -b &
libinput-gestures-setup start &
ulauncher --hide-window &

slack -u -s &
redshift-gtk -l 56:10 &
dunst &
unclutter -grab &
xsetroot -cursor_name left_ptr &
setxkbmap -option "ctrl:nocaps" &
gnome-screensaver &
i8kmon & # fan control
discord --start-minimized &
#~/.config/polybar/launch.py &
killall monitor-update.py
~/repos/bspwm-scripts/monitor-update.py &
killall sound-update.py
~/repos/bspwm-scripts/sound-update.py &

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled 

bspc rule -a matplotlib state=floating
bspc rule -a "Volume Control" state=floating 
bspc rule -a "Question" state=floating 
bspc rule -a Ulauncher state=floating 
bspc rule -a Lxappearance state=floating 
bspc rule -a Nitrogen state=floating 
bspc rule -a Pavucontrol state=floating 
bspc rule -a Simple-scan state=floating 
bspc rule -a Gnome-calculator state=floating 
bspc rule -a Nm-connection-editor state=floating 
bspc rule -a Software-properties-gtk state=floating 
bspc rule -a "Mathpix Snipping Tool" state=floating 
bspc rule -a Gnome-control-center state=floating
bspc rule -a win0 state=floating
bspc rule -a Yad state=floating
